In [1]:
import numpy as np
from __future__ import division
import itertools
import collections

## PWOP
generates an Ne estimate from a vector of K_i values

In [2]:
def pwop(k_i):
    """from waples (2011)"""
    assert type(k_i) is np.ndarray
    print '{} contributing parents'.format(len(k_i))
    print '{} gametes'.format(np.sum(k_i))
    numerator = np.sum(k_i)-1
    denominator = np.sum(k_i**2)/np.sum(k_i) - 1
    Ne = numerator/denominator 
    return(Ne)

#### example

In [3]:
K_i = np.array([2,2,3,7,2,5,1])
K_i

array([2, 2, 3, 7, 2, 5, 1])

In [4]:
pwop(K_i)

7 contributing parents
22 gametes


6.2432432432432439

## p_share
calculates the probability that two gametes taken at random from a sample specified by a K_i vector share the same parent

In [5]:
def p_share(k_i):
    """chance two random gametes present in the offspring generation are from the same parent"""
    N = np.int(np.sum(k_i)) # number of offspring or parents
    print '{} contributing parents'.format(len(k_i))
    print '{} gametes'.format(N)
    p = 1./(N*(N-1)) * np.sum(k_i*(k_i-1))
    return(p)

#### example

In [6]:
K_i

array([2, 2, 3, 7, 2, 5, 1])

In [7]:
p_share(K_i)

7 contributing parents
22 gametes


0.16017316017316016

## Wang 2009
simplified version of Wang (2009) eq. 10



- p_same_parent = the chance that two random gametes are from the same parent 
- p_same_parent is eqivalent to  (Q1+Q2+2*Q3)/2 - see equation 8
- p_same_parent/2 = the chance that two random gametes are identical by descent
- assumes alpha = 0 (i.e. Fis = 0)
- there is also an additional factor of 1/2, as we are dealing with gametes instead of individuals

This is basically the definition of inbreeding Ne

Wang notes that α = 1/(1 − 2Ne) in a randomly mating population

In [8]:
def wang(p_same_parent):
    """Given the chance that two random gametes share a parent, return the Ne"""
    Ne = 1./p_same_parent
    return(Ne)

In [9]:
wang(p_share(K_i))

7 contributing parents
22 gametes


6.243243243243244

## Simulate an ideal mating population
Generates the K_i vector from one generation of random mating of N parents producing N offspring (2N gametes)

In [10]:
def sim_ideal(N):
    """Generates the K_i vector from one generation of random mating of N parents"""
    a = collections.defaultdict(int)
    for xx in np.random.randint(0, N, 2*N): # For each of 2N gametes select a parent
        a[xx]+=1 # assign the gamete to that parent
    k_i = np.array(a.values())
    print '{} contributing parents'.format(len(k_i))
    print '{} gametes'.format(np.sum(k_i))
    return(k_i)

In [11]:
K_i = sim_ideal(200)
K_i

175 contributing parents
400 gametes


array([5, 2, 4, 1, 2, 3, 1, 1, 1, 3, 1, 3, 1, 2, 5, 2, 7, 1, 1, 3, 3, 1, 2,
       2, 2, 2, 1, 2, 1, 1, 3, 3, 1, 1, 3, 1, 2, 2, 3, 1, 1, 4, 1, 1, 5, 5,
       2, 3, 1, 3, 5, 2, 2, 2, 4, 4, 2, 3, 3, 1, 3, 3, 1, 1, 1, 2, 1, 4, 2,
       1, 4, 1, 1, 5, 4, 1, 3, 4, 3, 2, 3, 2, 3, 3, 4, 2, 1, 1, 3, 3, 2, 1,
       4, 4, 3, 2, 1, 1, 3, 1, 1, 1, 5, 2, 3, 1, 1, 2, 1, 3, 3, 3, 2, 1, 3,
       4, 3, 1, 1, 1, 1, 2, 4, 2, 3, 2, 1, 1, 8, 1, 1, 3, 3, 2, 2, 2, 1, 4,
       1, 2, 1, 1, 3, 2, 1, 3, 3, 1, 4, 2, 3, 2, 1, 2, 3, 2, 5, 4, 6, 1, 1,
       1, 2, 1, 2, 1, 2, 2, 4, 3, 1, 1, 1, 3, 3])

## Apply both methods to the same k_i vector

In [12]:
pwop(K_i)

175 contributing parents
400 gametes


194.16058394160584

In [13]:
p_share(K_i)

175 contributing parents
400 gametes


0.005150375939849624

In [14]:
wang(p_share(K_i))

175 contributing parents
400 gametes


194.16058394160584

## Also compare to Crow (1954) & Crow and Denniston (1988) eq 1.
the genesis of PWOP

In [15]:
def CnD(k_i):
    top = np.mean(k_i) - 1 + np.var(k_i)/np.mean(k_i)
    bottom = len(k_i)*np.mean(k_i)-1
    Ne = bottom/top
    return(Ne)

In [16]:
CnD(K_i)

194.16058394160586