In [1]:
import numpy as np
from __future__ import division
import itertools
import collections

## PWOP
generates an Ne estimate from a vector of K_i values

In [2]:
def pwop(k_i):
    """from waples (2011)"""
    assert type(k_i) is np.ndarray
    print '{} contributing parents'.format(len(k_i))
    print '{} gametes'.format(np.sum(k_i))
    numerator = np.sum(k_i)-1
    denominator = np.sum(k_i**2)/np.sum(k_i) - 1
    Ne = numerator/denominator 
    return(Ne)

#### example

In [91]:
K_i = np.array([2,2,3,7,2,5,1])
K_i

array([2, 2, 3, 7, 2, 5, 1])

In [92]:
pwop(K_i)

7 contributing parents
22 gametes


6.2432432432432439

## p_share
calculates the probability that two gametes taken at random from a sample specified by a K_i vector share the same parent

In [71]:
def p_share(k_i):
    """chance two random gametes present in the offspring generation are from the same parent"""
    N = np.int(np.sum(k_i)) # number of offspring or parents
    print '{} contributing parents'.format(len(k_i))
    print '{} gametes'.format(N)
    p = 1./(N*(N-1)) * np.sum(k_i*(k_i-1))
    return(p)

#### example

In [89]:
K_i

array([2, 2, 3, 7, 2, 5, 1])

In [90]:
p_share(K_i)

7 contributing parents
22 gametes


0.16017316017316016

## Wang 2009
Given the chance that two random gametes share a parent, return the Ne

Not sure this should be called "wang" any more - this is basically the definition of inbreeding Ne 

In [93]:
def wang(p_same_parent):
    """simplified version of Wang (2009) eq. 10
    p_same_parent = the chance that two random gametes are from the same parent 
    assumes alpha = 0 (i.e. Fis = 0)
    p_same_parent stands in for the sum of the Q1+Q2+2*Q3 - see equation 8
    remove the factor of 1/4, as we are dealing with gametes instead of individuals"""
    return(1/(p_same_parent))

In [94]:
wang(p_share(K_i))

7 contributing parents
22 gametes


6.243243243243244

## Simulate an ideal mating population
Generates the K_i vector from one generation of random mating of N parents

In [95]:
def sim_ideal(N):
    """Generates the K_i vector from one generation of random mating of N parents"""
    a = collections.defaultdict(int)
    for xx in np.random.randint(0, N, 2*N): # For each of 2N gametes select a parent
        a[xx]+=1 # assign an gamete to that parent
    k_i = np.array(a.values())   
    print '{} contributing parents'.format(len(k_i))
    print '{} gametes'.format(np.sum(k_i))
    return(k_i)

In [99]:
K_i = sim_ideal(200)
print 'Variance in k_i values: {}'.format(np.var(K_i))
K_i

176 contributing parents
400 gametes
Variance in k_i values: 1.42561983471


array([2, 3, 2, 4, 2, 4, 3, 2, 2, 2, 2, 2, 3, 2, 1, 4, 5, 2, 2, 3, 2, 2, 1,
       4, 2, 3, 1, 3, 2, 1, 2, 2, 1, 2, 2, 2, 2, 4, 3, 1, 1, 2, 4, 4, 1, 2,
       1, 1, 1, 2, 3, 1, 1, 4, 1, 1, 4, 4, 3, 3, 3, 2, 1, 2, 1, 1, 2, 1, 3,
       2, 4, 3, 2, 1, 3, 3, 2, 4, 1, 6, 3, 2, 3, 1, 2, 1, 2, 3, 1, 1, 1, 1,
       3, 5, 5, 5, 2, 2, 3, 1, 2, 2, 2, 2, 4, 1, 2, 3, 6, 1, 1, 1, 2, 2, 1,
       2, 1, 1, 1, 2, 1, 1, 2, 2, 3, 2, 2, 5, 5, 1, 2, 2, 3, 3, 2, 2, 3, 2,
       3, 1, 3, 5, 1, 1, 3, 2, 2, 2, 1, 1, 1, 3, 1, 3, 2, 1, 3, 2, 1, 1, 2,
       3, 3, 3, 1, 4, 3, 1, 1, 3, 3, 5, 5, 4, 1, 1])

In [106]:
pwop(K_i)

176 contributing parents
400 gametes


210.0

In [107]:
p_share(K_i)

176 contributing parents
400 gametes


0.004761904761904762

In [108]:
wang(p_share(K_i))

176 contributing parents
400 gametes


209.99999999999997